# Generated by Django 3.2.9 on 2021-11-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SBFlix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_date',
            new_name='release_year',
        ),
    ]
